#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
setopt clobber

# Tmux aliases
alias tmux='tmux -2'
alias ta='tmux attach -t'
alias tnew='tmux new -s'
alias tls='tmux ls'
alias tkill='tmux kill-session -t'

alias ev='vim ~/.vimrc'
alias et='vim ~/.tmux.conf'
alias ez='vim ~/.zshrc'

# Coloured cat
colorcat () {
  # Only use pygmentize if:
  # * pygmentize is inslalled
  # * writing to terminal
  if type pygmentize > /dev/null && [ -t 1 ];
  then
    for f in $*;
    do
      pygmentize -g $f
    done
  else
    /bin/cat $*
  fi
}
alias cat=colorcat
alias ccat=/bin/cat

alias pqiv='pqiv -ci'
alias -s png='pqiv -ci'
alias -s jpg='pqiv -ci'
alias -s jpeg='pqiv -ci'
alias -s xpm='pqiv -ci'
alias -s gif='pqiv -ci'

alias k='fasd_cd'

# Make okular quiet
alias okular='okular >& /dev/null'

# Because fg=8 is invisible
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=238'

bindkey '^R' history-incremental-search-backward

if [ "$COLORTERM" = "gnome-terminal" ]; then
  if [[ "$TERM" =~ xterm.* ]]; then
    export TERM=gnome-256color
  else
    export TERM=tmux-256color
  fi
fi

# Show NORMAL vi mode when appropriate
precmd() {
  RPROMPT=""
}
zle-keymap-select() {
  RPROMPT=""
  [[ $KEYMAP = vicmd ]] && RPROMPT="%F{green}%S NORMAL %s%F{default}"
  () { return $__prompt_status }
  zle reset-prompt
}
zle-line-init() {
  typeset -g __prompt_status="$?"
}
zle -N zle-keymap-select
zle -N zle-line-init

export GPG_TTY=$(tty)
